import { GoogleGenAI } from '@google/genai';
import { env } from '../config/env.js';
import { AppError } from '../middleware/errorHandler.js';
import { generateWithGroq } from './groqService.js';

let ai = null;

function getClient() {
  if (!env.geminiApiKey) {
    throw new AppError('Gemini API key not configured', 503);
  }
  if (!ai) {
    ai = new GoogleGenAI({ apiKey: env.geminiApiKey });
  }
  return ai;
}

function handleGeminiError(err) {
  const status = err?.status ?? err?.statusCode;
  if (status === 429) {
    throw new AppError('AI service is temporarily busy. Please try again in a minute.', 429);
  }
  if (status === 400) {
    throw new AppError('AI request could not be processed. Please try again.', 400);
  }
  if (err?.message?.includes('fetch failed')) {
    throw new AppError('Could not reach AI service. Check your network connection.', 503);
  }
  throw err;
}

function shouldTryGroqFallback(err) {
  const status = err?.status ?? err?.statusCode;
  return status === 429 || status === 503;
}

async function generateWithGemini({ contents, config = {} }) {
  const client = getClient();
  const response = await client.models.generateContent({
    model: env.geminiModel,
    contents,
    config,
  });
  return response.text ?? '';
}

async function generateContent({ contents, config = {} }) {
  try {
    return await generateWithGemini({ contents, config });
  } catch (err) {
    if (!shouldTryGroqFallback(err) || !env.groqApiKey) {
      handleGeminiError(err);
    }

    console.warn('Gemini unavailable, falling back to Groq...', {
      status: err?.status ?? err?.statusCode,
    });

    try {
      return await generateWithGroq({ contents, config });
    } catch (groqErr) {
      console.error('Groq fallback also failed', groqErr);
      handleGeminiError(err);
    }
  }
}

const DANNY_SYSTEM_PROMPT = `You are Danny, a friendly AI math tutor for elementary and secondary school students.

PERSONALITY: Encouraging, motivating, child-safe, patient, and warm.

TEACHING RULES:
1. NEVER give the direct answer first
2. Always follow this order: Explain the concept → Guide the student → Give a hint → Only then provide the solution
3. Use simple language appropriate for the student's level
4. Celebrate effort and progress
5. If the student is stuck, break problems into smaller steps
6. Detect when a student struggles and offer encouragement

You help with mathematics topics including Geometry, Algebra, and Permutation & Combination.`;

export async function chatWithDanny(messages, weakTopics = []) {
  const contextNote = weakTopics.length
    ? `\nStudent weak topics: ${weakTopics.map((t) => `${t.topic} (${t.masteryPercent}%)`).join(', ')}. Focus extra support here.`
    : '';

  const contents = messages.map((m) => ({
    role: m.role === 'assistant' ? 'model' : 'user',
    parts: [{ text: m.content }],
  }));

  return generateContent({
    contents,
    config: {
      systemInstruction: DANNY_SYSTEM_PROMPT + contextNote,
    },
  });
}

export async function solveWithCalculator(input) {
  const prompt = `Solve this math problem step by step. Input: "${input}"

Return JSON with exactly these fields:
{
  "answer": "the final answer",
  "stepByStepSolution": ["step 1", "step 2", ...],
  "explanation": "plain language explanation",
  "similarQuestion": "a similar practice question"
}

NEVER skip steps. Explain every step clearly.`;

  const text = await generateContent({
    contents: prompt,
    config: { responseMimeType: 'application/json' },
  });

  try {
    return JSON.parse(text);
  } catch {
    return {
      answer: text,
      stepByStepSolution: [text],
      explanation: 'Solution generated by AI.',
      similarQuestion: 'Try a similar problem on your own!',
    };
  }
}

export async function generateWeeklyReport(childName, progressData) {
  const prompt = `Generate a friendly weekly progress report for parent about their child ${childName}.
Data: ${JSON.stringify(progressData)}

Write 2-3 sentences highlighting improvements, areas to focus, and encouragement.
Example style: "Your child improved by 15% in Geometry this week."`;

  return generateContent({ contents: prompt });
}

export async function generateMathGame(config) {
  const prompt = `Create an educational math game for a ${config.age}-year-old.
Topic: ${config.topic}, Difficulty: ${config.difficulty}, Theme: ${config.theme}

Return JSON:
{
  "gameTitle": "string",
  "rules": "string",
  "boardLayout": "string description",
  "activities": ["activity1", "activity2", ...],
  "rewards": ["reward1", "reward2", ...]
}`;

  const text = await generateContent({
    contents: prompt,
    config: { responseMimeType: 'application/json' },
  });

  return JSON.parse(text);
}
